#!/usr/bin/env bash
# scaffold.sh — Phase 1: Initialize project and copy governance configs

# Source common functions
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/common.sh"

# Initialize project with governance framework
# Usage: run_scaffold "$PROJECT_NAME" "$STACK" "$OUTPUT_DIR" "$WORKFLOW_ROOT"
run_scaffold() {
  local project="$1"
  local stack="$2"
  local output_dir="$3"
  local workflow_root="$4"
  local project_dir="${output_dir}/${project}"

  log_phase "1 — Scaffold"

  # Create project directory
  if [[ -d "$project_dir" ]]; then
    log_warn "Project directory already exists: $project_dir"
    log_warn "Use --skip-scaffold to skip this phase"
    return 1
  fi

  mkdir -p "$project_dir"
  log_info "Created project directory: $project_dir"

  # Initialize based on stack
  cd "$project_dir"
  case "$stack" in
    nextjs-ts)
      log_info "Initializing Next.js + TypeScript project..."
      echo "{\"name\":\"${project}\",\"version\":\"0.1.0\",\"private\":true,\"scripts\":{\"dev\":\"next dev --turbopack\",\"build\":\"next build\",\"start\":\"next start\",\"lint\":\"next lint\",\"typecheck\":\"tsc --noEmit\",\"test\":\"echo \\\"No tests configured yet\\\" && exit 0\"}}" > package.json
      pnpm add next@latest react@latest react-dom@latest 2>&1 | tail -3
      pnpm add -D typescript @types/react @types/react-dom @types/node tailwindcss @tailwindcss/postcss postcss eslint eslint-config-next 2>&1 | tail -3
      scaffold_nextjs_files "$project"
      ;;
    python-fastapi)
      log_info "Initializing Python + FastAPI project..."
      python3 -m venv venv
      echo "fastapi[standard]" > requirements.txt
      echo "pytest" >> requirements.txt
      echo "httpx" >> requirements.txt
      ;;
    go-gin)
      log_info "Initializing Go + Gin project..."
      go mod init "$project"
      go get -u github.com/gin-gonic/gin
      ;;
    *)
      log_error "Unknown stack: $stack (supported: nextjs-ts, python-fastapi, go-gin)"
      return 1
      ;;
  esac

  # Copy governance configs
  log_info "Copying governance framework..."
  copy_governance "$workflow_root" "$project_dir" "$stack"

  # Generate AGENTS.md
  log_info "Generating project AGENTS.md..."
  generate_agents_md "$project" "$stack" "$project_dir"

  # Generate CLAUDE.md
  log_info "Generating project CLAUDE.md..."
  generate_claude_md "$project_dir"

  # Generate .gitignore
  generate_gitignore "$stack" "$project_dir"

  # Git init
  cd "$project_dir"
  git init
  git add -A
  git commit -m "feat: 初始化 ${project}（auto-dev scaffold, stack: ${stack}）"

  log_success "Scaffold complete: $project_dir"
}

# Create Next.js boilerplate files
scaffold_nextjs_files() {
  local project="$1"
  mkdir -p src/app src/components src/lib src/types

  cat > tsconfig.json << 'TSEOF'
{"compilerOptions":{"target":"ES2017","lib":["dom","dom.iterable","esnext"],"allowJs":true,"skipLibCheck":true,"strict":true,"noEmit":true,"esModuleInterop":true,"module":"esnext","moduleResolution":"bundler","resolveJsonModule":true,"isolatedModules":true,"jsx":"preserve","incremental":true,"plugins":[{"name":"next"}],"paths":{"@/*":["./src/*"]}},"include":["next-env.d.ts","**/*.ts","**/*.tsx",".next/types/**/*.ts"],"exclude":["node_modules"]}
TSEOF

  cat > next.config.ts << 'NCEOF'
import type { NextConfig } from "next";
const nextConfig: NextConfig = {};
export default nextConfig;
NCEOF

  cat > postcss.config.mjs << 'PCEOF'
const config = { plugins: { "@tailwindcss/postcss": {} } };
export default config;
PCEOF

  cat > src/app/globals.css << 'CSSEOF'
@import "tailwindcss";
CSSEOF

  cat > src/app/layout.tsx << LAYEOF
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "${project}",
  description: "Generated by auto-dev",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="zh-CN">
      <body>{children}</body>
    </html>
  );
}
LAYEOF

  cat > src/app/page.tsx << PGEOF
export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <h1 className="text-4xl font-bold">${project}</h1>
      <p className="mt-4 text-lg text-gray-600">Under construction.</p>
    </main>
  );
}
PGEOF
}

# Copy governance configs from workflow root
copy_governance() {
  local src="$1"
  local dst="$2"
  local stack="$3"

  # .claude/settings.json
  mkdir -p "$dst/.claude/rules" "$dst/.claude/skills"
  cp "$src/.claude/settings.json" "$dst/.claude/settings.json"

  # Rules: always copy common rules
  for f in agents.md coding-style.md development-workflow.md git-workflow.md hooks.md patterns.md performance.md security.md testing.md; do
    [[ -f "$src/.claude/rules/$f" ]] && cp "$src/.claude/rules/$f" "$dst/.claude/rules/$f"
  done

  # Rules: copy language-specific rules based on stack
  case "$stack" in
    nextjs-ts)
      for f in "$src/.claude/rules"/ts-*.md; do [[ -f "$f" ]] && cp "$f" "$dst/.claude/rules/"; done
      ;;
    python-fastapi)
      for f in "$src/.claude/rules"/py-*.md; do [[ -f "$f" ]] && cp "$f" "$dst/.claude/rules/"; done
      ;;
    go-gin)
      for f in "$src/.claude/rules"/go-*.md; do [[ -f "$f" ]] && cp "$f" "$dst/.claude/rules/"; done
      ;;
  esac

  # Skills
  cp -r "$src/.claude/skills/"* "$dst/.claude/skills/" 2>/dev/null || true

  # Codex config
  mkdir -p "$dst/.codex/agents"
  cp "$src/.codex/config.toml" "$dst/.codex/config.toml" 2>/dev/null || true
  cp "$src/.codex/agents/reviewer.toml" "$dst/.codex/agents/reviewer.toml" 2>/dev/null || true

  # Codex AGENTS.md
  cat > "$dst/.codex/AGENTS.md" << 'CDXEOF'
# Codex-specific instructions

Inherits all rules from the root AGENTS.md.

## Additional Codex conventions
- Use workspace-write sandbox mode for all tasks.
- Approval policy is on-request — always ask before executing destructive commands.
- When running tests, capture full output including stderr.
CDXEOF

  # Scripts
  mkdir -p "$dst/scripts/cron" "$dst/hooks" "$dst/logs"
  cp "$src/scripts/start-sessions.sh" "$dst/scripts/start-sessions.sh" 2>/dev/null || true
  for f in "$src/scripts/cron/"*.sh; do
    [[ -f "$f" ]] && cp "$f" "$dst/scripts/cron/"
  done
  chmod +x "$dst/scripts/"*.sh "$dst/scripts/cron/"*.sh 2>/dev/null || true

  log_success "Governance configs copied (rules + skills + codex + scripts)"
}

# Generate project-specific AGENTS.md
generate_agents_md() {
  local project="$1"
  local stack="$2"
  local dst="$3"

  local pkg_manager="pnpm"
  local test_cmd="pnpm test"
  local lint_cmd="pnpm lint"

  case "$stack" in
    python-fastapi) pkg_manager="pip"; test_cmd="pytest"; lint_cmd="ruff check ." ;;
    go-gin) pkg_manager="go mod"; test_cmd="go test ./..."; lint_cmd="golangci-lint run" ;;
  esac

  cat > "$dst/AGENTS.md" << AGEOF
# AGENTS.md — ${project} Shared Specification

## Setup commands
- Install deps: \`${pkg_manager} install\`
- Dev: \`pnpm dev\`
- Build: \`pnpm build\`
- Test: \`${test_cmd}\`
- Lint: \`${lint_cmd}\`
- Type check: \`pnpm typecheck\`
- Security scan: \`npx ecc-agentshield scan\`

## Working agreements
- Keep diffs small and reversible.
- Ask before adding new production dependencies.
- Never commit directly to main; always use feature branches.
- Commit messages follow Conventional Commits format.
- All configuration changes must be validated by AgentShield scan before commit.

## Architecture notes
- This project was scaffolded by ai-dev-workflow auto-dev (stack: ${stack}).
- Shared rules live in AGENTS.md (this file).
- Claude-specific config lives in \`.claude/\`.
- Codex-specific config lives in \`.codex/\`.

## Review guidelines
- Treat auth/session regressions as P0.
- Treat data-loss or migration issues as P0.
- Treat any hardcoded secrets or API keys as P0.
- Treat changes to permissions.deny without explicit justification as P0.
- Treat missing tests for changed business logic as P1.
- Treat console.log left in production code as P1.
- Treat typos in user-facing strings as P1.
AGEOF
}

# Generate CLAUDE.md
generate_claude_md() {
  local dst="$1"
  cat > "$dst/CLAUDE.md" << 'CLEOF'
# CLAUDE.md

@AGENTS.md

## Claude-specific workflow
- For non-trivial work: explore -> plan -> edit -> test.
- Prefer editing existing files over creating new ones.
- Keep summaries short; show changed files, commands, and test results.

## Output preferences
- Use Chinese for commit messages and comments.
- Code and variable names in English.
- Configuration file comments in English.

## Safety reminders
- Never read or write .env files — permissions.deny will block it, but don't even attempt.
- Always run `npx ecc-agentshield scan` after modifying any file in `.claude/` or `hooks/`.
- When in doubt about a destructive operation, ask the user first.
CLEOF
}

# Generate .gitignore based on stack
generate_gitignore() {
  local stack="$1"
  local dst="$2"

  cat > "$dst/.gitignore" << 'GIEOF'
# Local overrides
.claude/settings.local.json

# Logs
logs/
*.log

# Environment
.env
.env.*
!.env.example

# OS
.DS_Store
Thumbs.db

# Editor
.vscode/
.idea/
*.swp
*.swo
GIEOF

  case "$stack" in
    nextjs-ts)
      cat >> "$dst/.gitignore" << 'NJEOF'

# Next.js
.next/
out/
node_modules/
coverage/
NJEOF
      ;;
    python-fastapi)
      cat >> "$dst/.gitignore" << 'PYEOF'

# Python
venv/
__pycache__/
*.pyc
.pytest_cache/
htmlcov/
PYEOF
      ;;
    go-gin)
      cat >> "$dst/.gitignore" << 'GOEOF'

# Go
/bin/
/vendor/
GOEOF
      ;;
  esac
}
